apiVersion: v1
kind: Service
metadata:
   name: game-svc-tetris
spec:
   selector:
      app: tetris  # Adjust this label to match the Tetris deployment's label
   ports:
   - protocol: TCP
     port: 80
     targetPort: 80
   type: LoadBalancer
